#version 450
#extension GL_GOOGLE_include_directive : enable

#include "../common/random.glsl"

layout (binding = 0, rgba32f) uniform writeonly image2D target;
layout (binding = 1, rgba32f) uniform readonly image2D src;

layout (local_size_x = 1, local_size_y = 256, local_size_z = 1) in;

void main()
{
    uint line_strength = 2;
    uint max_dist = 6;

    int row = int(gl_GlobalInvocationID.y);
    ivec2 size = imageSize(target);

    if (row >= size.y)
        return;

    uint seed = 1385743257;
    uvec4 rng_state = uvec4(seed, seed * 2, seed * 3, seed * 4) + 5378947 * (row / line_strength);

    float rand = stepAndOutputRNGFloat(rng_state);

    int dist = int(round(rand * float(2 * max_dist))) - int(max_dist);

    for (int i = 0; i < size.x; i++) {
        ivec2 pixel = ivec2(i, row);
        ivec2 src_pos = pixel - ivec2(dist, 0);
        src_pos.x = clamp(src_pos.x, 0, size.x - 1);
        vec3 c = imageLoad(src, src_pos).xyz;
        imageStore(target, pixel, vec4(c, 1));
    }
}
